version: "2"

services:
  redis:
    image: redis:7.0.5-alpine
    volumes:
      - "redis:/data"

  bot:
    image: picking_daily_anekdot
    env_file:
      - "bot.env"

volumes:
  redis:
    external: true
