name: push-to-master
run-name: Push to master action
on:
  push:
    branches:
      - master
jobs:
  push-to-yct:
    runs-on: ubuntu-latest
    environment: yandex-cloud
    steps:
      - uses: actions/checkout@v3
      - uses: raisultan/ycr-push@main
        env:
          KEY_JSON: ${{ secrets.KEY_JSON }}
          REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
          DOCKERFILE_PATH: ${{ secrets.DOCKERFILE_PATH }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          IMAGE_TAG: latest
